---

- name: Deploy initial AAP config (org, users, teams, etc.)
  hosts: localhost
  gather_facts: false
  vars:
    aap_validate_certs: false
    local_clone_path: "/tmp/{{ awx_webhook_payload.repository.name }}"
    source_repo_url: "{{ awx_webhook_payload.repository.clone_url }}"
  pre_tasks:

    - name: Ensure local_clone_path does not exist before cloning
      ansible.builtin.file:
        path: "{{ local_clone_path }}"
        state: absent

    - name: Clonar el repositorio de origen
      ansible.builtin.git:
        repo: "{{ source_repo_url }}"
        dest: "{{ local_clone_path }}"

    - name: List contents of the cloned repository
      ansible.builtin.command: ls -la "{{ local_clone_path }}"
      register: ls_output

    - name: Print the contents of the cloned repository
      ansible.builtin.debug:
        var: ls_output.stdout_lines

    - name: Include vars from directory
      ansible.builtin.include_vars:
        dir: "{{ local_clone_path }}/ansible/vars"
        extensions: ["yml"]
      tags:
        - always
  roles:
    - infra.aap_configuration.dispatch
