---

- name: Run yamllint in codebase
  hosts: localhost
  gather_facts: false
  vars:
    local_clone_path: "/tmp/{{ awx_webhook_payload.repository.name }}"
    source_repo_url: "{{ awx_webhook_payload.repository.clone_url }}"
  tasks:
    - name: Clone Git repository with playbooks
      ansible.builtin.git:
        repo: "{{ source_repo_url }}"
        dest: "{{ local_clone_path }}"
        force: true
      register: git_clone

    - name: Run yamllint on the codebase
      ansible.builtin.command:
        cmd: yamllint -c {{ local_clone_path }}/.yamllint {{ local_clone_path }}/playbooks/
      register: yamllint_result
      failed_when: yamllint_result.rc != 0 and yamllint_result.rc != 2
      changed_when: false
      ignore_errors: true

    - name: Display yamllint output
      ansible.builtin.debug:
        var: yamllint_result.stdout_lines

    - name: Fail if yamllint found issues
      ansible.builtin.fail:
        msg: "yamllint found issues in the codebase."
      when: yamllint_result.rc == 2
