---

- name: Run Molecule Tests
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Molecule Test
      command: molecule test
      args:
        chdir: "{{ item }}"
      with_items:
        - ../roles/role1
        - ../roles/role2
      register: molecule_results
      ignore_errors: yes

    - name: Display Molecule Test Results
      debug:
        var: molecule_results.results