---

- name: Run ansible-lint on playbooks
  hosts: localhost
  gather_facts: false
  vars:
    local_clone_path: "/tmp/{{ awx_webhook_payload.repository.name }}"
    source_repo_url: "{{ awx_webhook_payload.repository.clone_url }}"
  tasks:
    - name: Clone Git repository with playbooks
      ansible.builtin.git:
        repo: "{{ source_repo_url }}"
        dest: "{{ local_clone_path }}"
        force: true
      register: git_clone

    - name: List contents of the cloned repository
      ansible.builtin.command: ls "{{ local_clone_path }}/playbooks/"
      register: ls_output

    - name: Print the contents of the cloned repository
      ansible.builtin.debug:
        var: ls_output.stdout_lines

    - name: Execute ansible-lint
      ansible.builtin.command:
        cmd: ansible-lint {{ local_clone_path }}/playbooks/{{ item }}
      ignore_errors: true
      check_mode: false
      changed_when: true
      loop: "{{ ls_output.stdout_lines }}"
      register: lint_result

    - name: Display ansible-lint results
      ansible.builtin.debug:
        var: lint_result

    - name: Fail if ansible-lint found issues
      ansible.builtin.fail:
        msg: "ansible-lint found issues in the playbooks."
      when: item.rc != 0
      loop: "{{ lint_result }}"
