# ---

# - name: Sign the content to be executed in AAP
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Create gpg key to sign content
#       ansible.builtin.command: >
#         gpg --batch --passphrase '{{ gpg_passphrase }}' --quick-generate-key 'CI/CD <Runner>'

#     - name: Sign content
#       ansible.builtin.command: >
#         ansible-navigator sign --private-key /path/to/private/key /path/to/content
#       register: sign_result
#       ignore_errors: true
#       changed_when: false

#     - name: Display Sign Result
#       ansible.builtin.debug:
#         var: sign_result.stdout_lines


---
- name: Generar clave GPG automáticamente
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:

    - name: Crear credencial GPG en AAP para firmar el contenido
      ansible.controller.credential:
        name: "{{ aap_project_name }} GPG"
        organization: "{{ aap_organization }}"
        credential_type: "GPG Public Key"
        inputs:
          gpg_public_key: "{{ lookup('file', '/home/runner/gpg/public_key.asc') }}"
        state: present
        validate_certs: false
      register: gpg_credential

    - name: Añadir clave pública al repositorio AAP
      ansible.controller.project:
        name: "{{ aap_project_name }}"
        organization: "{{ aap_organization }}"
        scm_type: "git"
        scm_url: "https://github.com/{{ github_user }}/{{ new_repo_name }}.git"
        credential: "{{ scm_credential.id }}"
        signature_validation_credential: "{{ gpg_credential.id }}"
        wait: true # Espera a que la primera sincronización del proyecto termine.
        state: present
        validate_certs: false
